default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: gpk_top_development

test:
  <<: *default
  database: gpk_top_test

production:
  <<: *default

